// cli/src/backends/xorg_conf.c
#define _POSIX_C_SOURCE 200809L
#include "xorg_conf.h"
#include "../util/output.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define XORG_CONF_DIR "/etc/X11/xorg.conf.d"
#define OPENDE_CONF "40-opende-input.conf"

int xorg_can_write(void) {
    return access(XORG_CONF_DIR, W_OK) == 0;
}

static char *get_config_path(void) {
    static char path[256];
    snprintf(path, sizeof(path), "%s/%s", XORG_CONF_DIR, OPENDE_CONF);
    return path;
}

static int write_config(const char *content) {
    if (!xorg_can_write()) {
        print_error("Permission denied. Run with sudo.");
        return -1;
    }

    char *path = get_config_path();
    FILE *fp = fopen(path, "w");
    if (!fp) {
        print_error("Cannot write to %s", path);
        return -1;
    }

    fprintf(fp, "%s", content);
    fclose(fp);

    print_warn("Changes require X restart or re-login to take effect");
    return 0;
}

// Read current config or return defaults
static int read_option(const char *option) {
    char *path = get_config_path();
    FILE *fp = fopen(path, "r");
    if (!fp) return -1;  // No config = default

    char line[256];
    int result = -1;

    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, option)) {
            if (strstr(line, "\"true\"") || strstr(line, "\"on\"") || strstr(line, "\"1\"")) {
                result = 1;
            } else if (strstr(line, "\"false\"") || strstr(line, "\"off\"") || strstr(line, "\"0\"")) {
                result = 0;
            }
            break;
        }
    }

    fclose(fp);
    return result;
}

int xorg_get_natural_scroll(void) {
    return read_option("NaturalScrolling");
}

int xorg_set_natural_scroll(int enabled) {
    char content[1024];
    snprintf(content, sizeof(content),
        "# OpenDE Input Configuration\n"
        "# Generated by opende CLI - do not edit manually\n\n"
        "Section \"InputClass\"\n"
        "    Identifier \"OpenDE touchpad\"\n"
        "    MatchIsTouchpad \"on\"\n"
        "    Driver \"libinput\"\n"
        "    Option \"NaturalScrolling\" \"%s\"\n"
        "EndSection\n",
        enabled ? "true" : "false");

    return write_config(content);
}

int xorg_get_tap_click(void) {
    return read_option("Tapping");
}

int xorg_set_tap_click(int enabled) {
    char content[1024];
    snprintf(content, sizeof(content),
        "# OpenDE Input Configuration\n"
        "# Generated by opende CLI - do not edit manually\n\n"
        "Section \"InputClass\"\n"
        "    Identifier \"OpenDE touchpad\"\n"
        "    MatchIsTouchpad \"on\"\n"
        "    Driver \"libinput\"\n"
        "    Option \"Tapping\" \"%s\"\n"
        "EndSection\n",
        enabled ? "on" : "off");

    return write_config(content);
}

char *xorg_get_mouse_accel(void) {
    char *path = get_config_path();
    FILE *fp = fopen(path, "r");
    if (!fp) return strdup("default");

    char line[256];
    char *result = strdup("default");

    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, "AccelSpeed")) {
            if (strstr(line, "\"-1\"")) {
                free(result);
                result = strdup("off");
            } else if (strstr(line, "\"-0.5\"")) {
                free(result);
                result = strdup("low");
            } else if (strstr(line, "\"0\"")) {
                free(result);
                result = strdup("medium");
            } else if (strstr(line, "\"0.5\"")) {
                free(result);
                result = strdup("high");
            }
            break;
        }
    }

    fclose(fp);
    return result;
}

int xorg_set_mouse_accel(const char *level) {
    const char *accel_value;

    if (strcmp(level, "off") == 0) accel_value = "-1";
    else if (strcmp(level, "low") == 0) accel_value = "-0.5";
    else if (strcmp(level, "medium") == 0) accel_value = "0";
    else if (strcmp(level, "high") == 0) accel_value = "0.5";
    else {
        print_error("Invalid acceleration level. Use: off, low, medium, high");
        return -1;
    }

    char content[1024];
    snprintf(content, sizeof(content),
        "# OpenDE Input Configuration\n"
        "# Generated by opende CLI - do not edit manually\n\n"
        "Section \"InputClass\"\n"
        "    Identifier \"OpenDE pointer\"\n"
        "    MatchIsPointer \"on\"\n"
        "    Driver \"libinput\"\n"
        "    Option \"AccelSpeed\" \"%s\"\n"
        "EndSection\n",
        accel_value);

    return write_config(content);
}
